#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Opens the cd directory with the Finder
##?
##? Usage:
##?    cdf

docs::eval_help "$@"

# cd to Finder open folder
cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
