#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Export all installed packages
#?? 1.0.0
##?
##? Usage:
##?    export

docs::eval_help "$@"

brew services stop --all
brew bundle dump --file="$HOMEBREW_BUNDLE_FILE_PATH" --force --describe
echo 'Brew apps exported!'

npm list --global --parseable --depth=0 | sed '1d' | awk '{gsub(/\/.*\//,"",$1); print}' | grep -v npm >"$DOTFILES_PATH/langs/js/global_modules.txt"
echo 'NPM apps exported!'