#!/usr/bin/env bash

# Fail fast and be aware of exit codes
set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?    install

docs::eval_help "$@"

# "$DOTFILES_PATH/bin/dot" self update

# source "$DOTFILES_PATH/modules/zimfw/zimfw.zsh" install

if platform::is_macos; then
  log::note "Installing MacOS  custom packages"

  # Install brew if not installed
  if ! [ -x "$(command -v brew)" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  brew bundle --file="$DOTFILES_PATH/mac/brew/Brewfile" --force
  echo "Brew apps imported!"

  # Correct paths (so, we handle all with $PATH)
  sudo truncate -s 0 /etc/paths

  # Custom macOS "defaults"
  sh "$DOTFILES_PATH/mac/defaults_macos.sh"
fi

# if platform::is_linux; then
#   log::note "Installing Linux 🐧 custom packages"

#   install_linux_custom
# fi

log::note "Installing npm packages"
xargs npm install -g <"$DOTFILES_PATH/langs/js/global_modules.txt"

log::note "Setting ZSH as the default shell"
chsh -s "$(command -v zsh)"

sh "$DOTFILES_PATH/symlinks/remove_links.sh"
sh "$DOTFILES_PATH/symlinks/links.sh"
echo "Symlinks added!"

# read -rp "🦑 Git config: What is you email? " git_email
# read -rp "🐙 Git config: And your name? " git_name

# git config --global user.email "$git_email"
# git config --global user.name "$git_name"
# git config --global --unset user.signingkey
# git config --global --unset commit.gpgsign
# git config --global --unset tag.gpgsign
# git config --global --unset gpg.program

# set pretty diff on terminal
git config --global core.pager "diff-so-fancy" | less -RFX

# lines around each diff
git config --global diff.context 5

# Better conflict handling. Add merges common ancestors
git config --global merge.conflictstyle diff3

# Always push new tags
git config --global push.followTags truncate

# Before rebase stash files, apply rebase and apply stash automatically
git config --global rebase.autostash true

# Alias to undo last commits. Example: git undo 2 (remove las 2 commits)
git config --global alias.undo '!f() { \
    git reset --hard $(git rev-parse --abbrev-ref HEAD)@{${1-1}}; \
}; f'

log::success "✅ All done!"